"""GitHub issue creation for human-gated rollback review.

When the re-evaluation window (execution-count-based) detects regression, this module
generates a GitHub issue with all context needed for a human
to decide whether to rollback.

Part of the self-adapting system. See:
docs/plans/2026-02-15-self-adapting-systems-design.md
"""

from __future__ import annotations

import re
import shutil
import subprocess  # nosec: B404
import sys


class RollbackReviewer:
    """Creates GitHub issues for regression review."""

    def generate_issue_title(self, skill_name: str) -> str:
        """Generate issue title for a skill regression."""
        return f"Skill regression detected: {skill_name}"

    def generate_issue_body(
        self,
        skill_name: str,
        baseline_gap: float,
        current_gap: float,
        improvement_diff: str,
        rollback_command: str,
    ) -> str:
        """Generate GitHub issue body with full regression context."""
        return f"""## Skill Regression Report

**Skill**: `{skill_name}`
**Label**: `skill-regression`

### Metrics

| Metric | Before (baseline) | After (current) |
|---|---|---|
| Stability Gap | {baseline_gap:.3f} | {current_gap:.3f} |

### What Changed

```
{improvement_diff}
```

### Rollback Command

```bash
{rollback_command}
```

### Decision Options

1. **Rollback**: Run the command above to revert to the previous version
2. **Keep**: Close this issue if the regression is acceptable or transient
3. **Investigate**: Request further analysis before deciding

### Context

This issue was auto-generated by the homeostatic monitoring system.
The skill was improved automatically but showed regression during the
10-execution evaluation window. Human review is required before rollback.
"""

    def generate_rollback_command(self, commit_hash: str) -> str:
        """Generate a git revert command for a commit.

        Raises ValueError if commit_hash contains invalid characters
        to prevent command injection.
        """
        if not re.match(r"^[a-f0-9]+$", commit_hash):
            raise ValueError(
                f"Invalid commit hash {commit_hash!r}: "
                "must contain only lowercase hex characters (a-f, 0-9)."
            )
        return f"git revert {commit_hash} --no-edit"

    def create_github_issue(
        self,
        skill_name: str,
        baseline_gap: float,
        current_gap: float,
        improvement_diff: str,
        rollback_command: str,
    ) -> str | None:
        """Create a GitHub issue via gh CLI.

        Returns the issue URL if successful, None otherwise.
        """
        title = self.generate_issue_title(skill_name)
        body = self.generate_issue_body(
            skill_name,
            baseline_gap,
            current_gap,
            improvement_diff,
            rollback_command,
        )

        gh_path = shutil.which("gh")
        if not gh_path:
            sys.stderr.write(
                "rollback_reviewer: gh CLI not found, "
                f"cannot create issue for {skill_name}\n"
            )
            return None

        try:
            result = subprocess.run(  # nosec: B603
                [
                    gh_path,
                    "issue",
                    "create",
                    "--title",
                    title,
                    "--body",
                    body,
                    "--label",
                    "skill-regression",
                ],
                capture_output=True,
                text=True,
                timeout=30,
                check=False,
            )
            if result.returncode == 0:
                return result.stdout.strip()
            sys.stderr.write(
                f"rollback_reviewer: gh issue create failed "
                f"(exit {result.returncode}) for {skill_name}: "
                f"{result.stderr.strip()}\n"
            )
            return None
        except FileNotFoundError:
            sys.stderr.write(
                f"rollback_reviewer: gh CLI not executable for {skill_name}\n"
            )
            return None
        except subprocess.TimeoutExpired:
            sys.stderr.write(
                f"rollback_reviewer: gh issue create timed out for {skill_name}\n"
            )
            return None
